nameOverride: ""
fullnameOverride: ""

image:
  registry: ""
  repository: ""
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

labels:

envFrom:
  secrets: []
  configMaps: []