nameOverride: ""
fullnameOverride: ""

image:
  registry: ""
  repository: ""
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

replicaCount: 1
labels:

envFrom:
  secrets: []
  configMaps: []

ports: []

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
#   memory: 128Mi

readinessProbe: {}
livenessProbe: {}
startupProbe: {}

service:
  type: ClusterIP
  ports:
    - name: web
      port: 80
      targetPort: 8080

route:
  enabled: false
  host: ""
  targetPort: web
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: None