on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      working_directory:
        required: true
        type: string
      java_version:
        required: false
        type: number
        default: 8


jobs:
  build-artifact:
    name: Build the Artifact after testing it
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: "Set up JDK ${{ inputs.java_version }}"
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ inputs.java_version }}
          cache: 'maven'

      - name: Build with Maven
        working-directory: ${{ input.working_directory }}
        run: ./mvnw -ntp --batch-mode clean package

      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name:  "${{ env.APP_NAME }}.jar"
          path: "${{ input.working_directory }}/target/${{ input.app_name }}*.jar"