on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      working_directory:
        required: true
        type: string
      java_version:
        required: false
        type: number
        default: 8


jobs:
  build-artifact:
    name: Build the Artifact after testing it
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Printing Inputs
        run: |
          echo "java_version:      ${{ inputs.java_version }}"
          echo "app_name:          ${{ inputs.app_name }}"
          echo "working_directory: ${{ inputs.working_directory}}"

      - name: "Set up JDK ${{ inputs.java_version }}"
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ inputs.java_version }}
          cache: 'maven'

      - name: Build with Maven
        working-directory: ${{ inputs.working_directory }}
        run: >-
          ./mvnw -ntp --batch-mode clean package

      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name:  "${{ inputs.APP_NAME }}.jar"
          path: "${{ inputs.working_directory }}/target/${{ inputs.app_name }}*.jar"