on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true
      working_directory:
        type: string
        required: true
    secrets:
      openshift_server_url:
        required: true
      openshift_token:
        required: true
      openshift_namespace:
        required: true
      github_token:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - name: Printing Inputs
        run: |
          echo "env: ${{ inputs.env }}"
          echo "openshift_server_url: ${{ secrets.openshift_server_url }}"

      - name: Log in to OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.openshift_server_url }}
          openshift_token: ${{ secrets.openshift_token }}
          namespace: ${{ secrets.openshift_namespace }}

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1
        with:
          charts_dir: ${{ inputs.working_directory }}
        env:
          CR_TOKEN: "${{ secrets.github_token }}"