name: Deploy on Openshift

on:
  workflow_dispatch:
    branches:
      - main
    inputs:
      env:
        description: "The target environment 'test' or 'prod'"
        required: true
        default: 'test'

jobs:
  deploy:
    name: Deploy onto Openshit
    uses: bcgov/jag-bcsc-auth-service/.github/workflows/deploy-helm-on-openshift.yml@main
    with:
      env: ${{ github.event.inputs.env }}
      working_directory: '.gitops/bcsc-auth-service'
    secrets:
      openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
      openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
      openshift_namespace: ${{ secrets.OPENSHIFT_NAMESPACE }}
      github_token: ${{ secrets.GITHUB_TOKEN }}