name: Deploy on Openshift

on:
  workflow_dispatch:
    branches:
      - main
    inputs:
      env:
        description: "The target environment 'test' or 'prod'"
        required: true
        default: 'test'
      app_version:
        description: "What image version to deploy"
        required: true

jobs:
  deploy:
    name: Deploy onto Openshift
    uses: SierraSystems/reusable-workflows/.github/workflows/helm-deploy.yml@main
    with:
      env: ${{ github.event.inputs.env }}
      working_directory: '.gitops/helm-charts/bcsc-auth-service'
      app_name: 'bcsc-auth'
      values-file: "../${{ github.event.inputs.env }}-values.yml"
    secrets:
      openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
      openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
      openshift_namespace: "${{ secrets.OPENSHIFT_LICENSE_PLATE }}-${{ github.event.inputs.env }}"
      values: |
        image.tag=${{ github.event.inputs.app_version }}
        licensePlate=${{ secrets.OPENSHIFT_LICENSE_PLATE }}
        image.registry=${{ secrets.OPENSHIFT_INTERNAL_REPOSITORY }}
        image.repository=${{ secrets.OPENSHIFT_LICENSE_PLATE }}-tools/bcsc-auth
        route.host=bcsc-auth-service-${{ secrets.OPENSHIFT_LICENSE_PLATE }}-${{ github.event.inputs.env }}.${{ secrets.OPENSHIFT_SILVER_ROUTE_URL }}
