name: Deploy on Openshift

on:
  workflow_dispatch:
    branches:
      - main
    inputs:
      env:
        description: "The target environment 'test' or 'prod'"
        required: true
        default: 'test'
      app_verion:
        description: "What image version to deploy"
        required: true

jobs:
  deploy:
    name: Deploy onto Openshit
    uses: bcgov/jag-bcsc-auth-service/.github/workflows/helm-deploy.yml@main
    with:
      env: ${{ github.event.inputs.env }}
      working_directory: '.gitops/bcsc-auth-service'
      app_name: 'bcsc-auth'
      app_version: ${{ github.event.inputs.app_verion }}
    secrets:
      openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
      openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
      openshift_namespace: "${{ secrets.OPENSHIFT_LICENSE_PLATE }}-${{ github.event.inputs.env }}"
      values: |
        nameOverride=bcsc-auth-service-test
        licensePlate=${{ secrets.OPENSHIFT_LICENSE_PLATE }}
        image.registry=${{ secrets.OPENSHIFT_INTERNAL_REPOSITORY }}
        image.repository=${{ secrets.OPENSHIFT_LICENSE_PLATE }}-tools/bcsc-auth
