name: Dev Build, Push and Deploy

on:
  push:
    branches:
      - main
      - feature/migrating-pipelines-to-github
  workflow_dispatch:
    branches:
      - main
      - feature/migrating-pipelines-to-github
    env:
      description: 'Target Environment (dev, test, or prod)'
      required: true
      default: 'dev'
#      default: 'test'

env:
  IMAGE_TAG: ""
  APP_NAME: "bcsc-auth"

jobs:
  build-artifact:
    name: Build the Artifact after testing it
    if: environment == 'dev'
    uses: bcgov/jag-bcsc-auth-service/.github/workflows/build-java-artifact.yml@main
    with:
      app_name: ${{ github.env.APP_NAME }}
      working_directory: src/bcsc-auth

  build-image:
#    if: github.event.inputs.env == 'dev'
#    environment: ${{ github.event.inputs.env }}
    environment: 'dev'
    name: Build and deploy to OpenShift
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/bcsc-auth
    needs:
      - build-artifact

    steps:
      - uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: "${{ env.APP_NAME }}.jar"
          path: "src/bcsc-auth/target/${{ env.APP_NAME }}.jar"

      - name: Authenticate and set context
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          namespace: ${{ secrets.OPENSHIFT_NAMESPACE }}

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Get Java Project Version
        run: |
          _version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "LATEST_VERSION=$_version" | tee -a $GITHUB_ENV

      - name: Determine image tags
        if: env.IMAGE_TAG == ''
        run: |
          echo "IMAGE_TAG=${LATEST_VERSION}-${GITHUB_SHA::8}" | tee -a $GITHUB_ENV

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.OPENSHIFT_EXTERNAL_SA_USERNAME }}
          password: ${{ secrets.OPENSHIFT_EXTERNAL_SA_PASSWORD }}
          registry: ${{ secrets.OPENSHIFT_EXTERNAL_REPOSITORY }}

      - name: Build from Dockerfile
        id: build-image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ secrets.OPENSHIFT_EXTERNAL_REPOSITORY }}/${{ secrets.OPENSHIFT_NAMESPACE }}/${{ env.APP_NAME }}:latest
            ${{ secrets.OPENSHIFT_EXTERNAL_REPOSITORY }}/${{ secrets.OPENSHIFT_NAMESPACE }}/${{ env.APP_NAME }}:${{ env.IMAGE_TAG }}
          context: "./src/bcsc-auth/"
          build-args: |
            APP_NAME=${{ env.APP_NAME }}
            APP_VERSION=${{ env.LATEST_VERSION }}
