name: Dev Build, Push and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

jobs:
  unit-test:
    uses: gpoleze/reusable-workflows/.github/workflows/java-unit-tests.yml@main
    with:
      working_directory: 'src/bcsc-auth'

  app-version:
    uses: SierraSystems/reusable-workflows/.github/workflows/java-maven-app-version.yml@main
    with:
      working_directory: 'src/bcsc-auth'

  build-image:
    name: Build image and push it to OpenShift
    needs:
    - unit-test
    - app-version
    uses: SierraSystems/reusable-workflows/.github/workflows/docker-build-and-push-image.yml@main
    with:
      env: 'tools'
      app_name: 'bcsc-auth'
      app_version: "${{ needs.app-version.outputs.app-version }}"
      working_directory: 'src/bcsc-auth'
      dockerfile: 'multi-stage.Dockerfile'
    secrets:
      openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
      openshift_token: ${{ secrets.OPENSHIFT_BUILDER_TOKEN }}
      openshift_external_repository: ${{ secrets.OPENSHIFT_EXTERNAL_REPOSITORY }}
      openshift_license_plate: ${{ secrets.OPENSHIFT_LICENSE_PLATE }}
      docker_username: ${{ secrets.OPENSHIFT_EXTERNAL_BUILDER_USERNAME }}
      docker_password: ${{ secrets.OPENSHIFT_EXTERNAL_BUILDER_PASSWORD }}

  deploy:
    name: Deploy onto Openshit
    needs:
    - build-image
    uses: SierraSystems/reusable-workflows/.github/workflows/helm-deploy.yml@main
    with:
      env: 'dev'
      working_directory: '.gitops/bcsc-auth-service'
      app_name: 'bcsc-auth'
      values-file: 'dev-values.yml'
    secrets:
      openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
      openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
      openshift_namespace: "${{ secrets.OPENSHIFT_LICENSE_PLATE }}-dev"
      values: |
        nameOverride=bcsc-auth-service-test
        image.registry=${{ secrets.OPENSHIFT_INTERNAL_REPOSITORY }}
        image.repository=${{ secrets.OPENSHIFT_LICENSE_PLATE }}-tools/bcsc-auth
        route.host=bcsc-auth-service-test-${{ secrets.OPENSHIFT_LICENSE_PLATE }}-dev.${{ secrets.OPENSHIFT_SILVER_ROUTE_URL }}
