name: Dev Build, Push and Deploy

on:
  push:
    branches:
      - feature/migrating-pipelines-to-github
#  workflow_dispatch: {}

env:
  IMAGE_TAGS: ""
  APP_NAME: "bcsc-auth-service"

jobs:
  build:
    name: Build and deploy to OpenShift
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: src/bcsc-auth

    steps:
      - uses: actions/checkout@v2

      - name: Authenticate and set context
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          namespace: ${{ env.OPENSHIFT_NAMESPACE }}

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Get Java Project Version
        run: |
          _version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "LATEST_VERSION=$_version" | tee -a $GITHUB_ENV

      - name: Determine image tags
        if: env.IMAGE_TAGS == ''
        run: |
          echo "IMAGE_TAGS=latest ${LATEST_VERSION}-${GITHUB_SHA::8}" | tee -a $GITHUB_ENV

      - name: Build from Dockerfile
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.APP_NAME }}
          tags: ${{ env.IMAGE_TAGS }}
          workdir: "./src/bcsc-auth"
          dockerfiles: ./Dockerfile
          build-args: |-
                        MVN_PROFILES=openshift
                        APP_NAME=${{ env.APP_NAME }}
                        APP_VERSION=${{ env.LATEST_VERSION }}
