name: Dev Build, Push and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

jobs:
  build-artifact:
    name: Build the Artifact after testing it
    uses: bcgov/jag-bcsc-auth-service/.github/workflows/build-java-artifact.yml@main
    with:
      app_name: 'bcsc-auth'
      working_directory: 'src/bcsc-auth'

  build-image:
    name: Build image and push it to OpenShift
    needs: build-artifact
    uses: bcgov/jag-bcsc-auth-service/.github/workflows/build-and-push-java-docker-image.yml@main
    with:
      app_name: 'bcsc-auth'
      working_directory: 'src/bcsc-auth'
    secrets:
      openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
      openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
      openshift_external_repository: ${{ secrets.OPENSHIFT_EXTERNAL_REPOSITORY }}
      openshift_namespace: ${{ secrets.OPENSHIFT_NAMESPACE }}
      username: ${{ secrets.OPENSHIFT_EXTERNAL_SA_USERNAME }}
      password: ${{ secrets.OPENSHIFT_EXTERNAL_SA_PASSWORD }}

  deploy:
    name: Deploy onto Openshit
    needs: build-artifact
    uses: bcgov/jag-bcsc-auth-service/.github/workflows/deploy.yml@main
    with:
      env: 'dev'
    secrets:
      openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
      openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
      openshift_namespace: ${{ secrets.OPENSHIFT_NAMESPACE }}