name: Dev Build, Push and Deploy

on:
  push:
    branches:
      - main
      - feature/migrating-pipelines-to-github
  workflow_dispatch:
    branches:
      - main
      - feature/migrating-pipelines-to-github

env:
  IMAGE_TAG: ""
  APP_NAME: "bcsc-auth-service"

jobs:
  build:
    name: Build and deploy to OpenShift
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: src/bcsc-auth

    steps:
      - uses: actions/checkout@v2

      - name: Authenticate and set context
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          namespace: ${{ env.OPENSHIFT_NAMESPACE }}

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Get Java Project Version
        run: |
          _version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "LATEST_VERSION=$_version" | tee -a $GITHUB_ENV

      - name: Determine image tags
        if: env.IMAGE_TAG == ''
        run: |
          echo "IMAGE_TAG=${LATEST_VERSION}-${GITHUB_SHA::8}" | tee -a $GITHUB_ENV

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.OPENSHIFT_EXTERNAL_SA_USERNAME }}
          password: ${{ secrets.OPENSHIFT_EXTERNAL_SA_PASSWORD }}
          registry: ${{ secrets.OPENSHIFT_EXTERNAL_REPOSITORY }}

      - name: Build from Dockerfile
        id: build-image
        uses: docker/build-push-action@v2
        with:
          image: ${{ env.APP_NAME }}
          tags: |
            ${{ secrets.OPENSHIFT_EXTERNAL_REPOSITORY }}${{ env.OPENSHIFT_NAMESPACE }}/${{ env.APP_NAME }}:latest
            ${{ secrets.OPENSHIFT_EXTERNAL_REPOSITORY }}${{ env.OPENSHIFT_NAMESPACE }}/${{ env.APP_NAME }}:${{ env.IMAGE_TAG }}
          context: "./src/bcsc-auth/"
          dockerfiles: "./src/bcsc-auth/Dockerfile"
          build-args: |
            MVN_PROFILES=openshift
            APP_NAME=${{ env.APP_NAME }}
            APP_VERSION=${{ env.LATEST_VERSION }}
