name: Dev Build, Push and Deploy

on:
  push:
    branches:
      - main
      - feature/migrating-pipelines-to-github
  workflow_dispatch:
    branches:
      - main
      - feature/migrating-pipelines-to-github
    inputs:
      env:
        description: 'Target Environment (dev, test, or prod)'
        required: true
        default: 'dev'

env:
  APP_NAME: 'bcsc-auth'
  WORKING_DIRECTORY: 'src/bcsc-auth'

jobs:
  build-artifact:
    name: Build the Artifact after testing it
    if: github.event_name == 'push' || github.event.inputs.env == 'dev'
    uses: bcgov/jag-bcsc-auth-service/.github/workflows/build-java-artifact.yml@main
    with:
      app_name: 'bcsc-auth'
      working_directory: 'src/bcsc-auth'

  build-image:
    name: Build image and push it to OpenShift
    needs: app-version
    uses: bcgov/jag-bcsc-auth-service/.github/workflows/build-and-push-java-docker-image.yml@main
    with:
      app_name: ${{ env.APP_NAME }}
      working_directory: ${{ env.WORKING_DIRECTORY }}
