on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true
      app_name:
        type: string
        required: true
      working_directory:
        type: string
        required: true
      values:
        type: string
        required: false
        default: ""
    secrets:
      openshift_server_url:
        required: true
      openshift_token:
        required: true
      openshift_license_plate:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - uses: actions/checkout@v2

      - name: Printing Inputs
        run: |
          echo "env: ${{ inputs.env }}"
          echo "app_name: ${{ inputs.app_name }}"
          echo "working_directory: ${{ inputs.working_directory }}"

      - name: Define namespace
        run: >-
          echo OPENSHIFT_NAMESPACE="9041f4-${{ inputs.env }}" | tee -a $GITHUB_ENV

      - name: Log in to OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.openshift_server_url }}
          openshift_token: ${{ secrets.openshift_token }}
          namespace: ${{ env.OPENSHIFT_NAMESPACE }}

      - name: Run chart-releaser
        uses: deliverybot/helm@v1
        with:
          release: ${{ inputs.app_name }}
          namespace: ${{ env.OPENSHIFT_NAMESPACE }}
          chart: ${{ inputs.working_directory }}
          values: ${{ inputs.values }}
          dry-run: true
