on:
  - pull_request

jobs:
  unit-test:
    uses: SierraSystems/reusable-workflows/.github/workflows/java-unit-tests.yml@main
    with:
      working_directory: 'src/bcsc-auth'

  build-image:
    uses: SierraSystems/reusable-workflows/.github/workflows/docker-build-image.yml@feature/docker-build-local
    with:
      app_name: 'bcsc-auth'
      working_directory: 'src/bcsc-auth'
      dockerfile: 'multi-stage.Dockerfile'
