on:
  - pull_request

jobs:
  unit-test:
    uses: SierraSystems/reusable-workflows/.github/workflows/java-unit-tests.yml@main
    with:
      working_directory: 'src/bcsc-auth'
      java_version: 17

  build-image:
    uses: SierraSystems/reusable-workflows/.github/workflows/docker-build-image-without-trivy.yml@main
    with:
      app_name: 'bcsc-auth'
      app_version: "*"
      working_directory: 'src/bcsc-auth'
      dockerfile: 'multi-stage.Dockerfile'
